pro
pro SQL*Plus Enhancement on 23 ai.
pro

pro 1) New-added *SET ERRORDETAILS* command
pro 2) New-added *PING* command
pro 3) New-added *OERR* command
pro 4) Supports the data type of *BOOLEAN*
pro 5) New-added *SHOW CONNECITON* command

pro
pro 1) New-added *SET ERRORDETAILS* command
pro
pro The display of URLs is controlled by the ERRORDETAILS setting,
pro with allowed values ??being OFF, ON, and VERBOSE,
pro with ON being the default.
pro

pro
pro conn su/su@//localhost:1521/freepdb1
pro
pro select * from testtab
pro /
pro

conn su/su@//localhost:1521/freepdb1

select * from testtab
/

pro pause
pause

pro show errordetails
pro

show errordetails

pro pause
pause

pro set errordetails off
pro

set errordetails off

pro pause
pause

pro select * from testtab
pro /
pro

select * from testtab
/

pro pause
pause

pro set errordetails verbose
pro

set errordetails verbose

pro pause
pause

pro select * from testtab
pro /

select * from testtab
/

pro pause
pause

pro
pro 2) New-added *PING* command
pro
pro We can execute the PING command directly in the SQL*Plus prompt on 23ai ...
pro
pro The TNS entry for the 23ai FREE version is as follows:
pro
pro # tnsnames.ora Network Configuration File: E:\23ai\dbhomeFree\NETWORK\ADMIN\tnsnames.ora
pro # Generated by Oracle configuration tools.
pro 
pro FREE =
pro   (DESCRIPTION =
pro     (ADDRESS = (PROTOCOL = TCP)(HOST = QuanwenZhao)(PORT = 1521))
pro     (CONNECT_DATA =
pro       (SERVER = DEDICATED)
pro       (SERVICE_NAME = FREE)
pro     )
pro   )
pro 
pro LISTENER_FREE =
pro   (ADDRESS = (PROTOCOL = TCP)(HOST = QuanwenZhao)(PORT = 1521))
pro

pro conn sys/admin@//localhost:1521/freepdb1 as sysdba
pro
pro ping

conn sys/admin@//localhost:1521/freepdb1 as sysdba
pro
ping

pro pause
pause

pro ping free
pro
ping free

pro pause
pause

pro ping listener_free
pro
ping listener_free

pro pause
pause

pro
pro 3) New-added *OERR* command
pro
pro We can execute the OERR command directly in the SQL*Plus prompt on 23ai ...
pro

pro oerr ora 48003
pro
oerr ora 48003

pro pause
pause

pro oerr ora-48003
pro
oerr ora-48003

pro pause
pause

pro oerr 48003
pro
oerr 48003

pro pause
pause

pro help 48003
pro
help 48003

pro pause
pause

pro help ora 48003
pro
help ora 48003

pro pause
pause

pro help ora-48003
pro
help ora-48003

pro pause
pause

pro
pro 4) Supports the data type of *BOOLEAN*
pro
pro Oracle 23ai's SQL*Plus now supports the BOOLEAN data type.
pro
pro select true, false from dual
pro /
pro

select true, false from dual
/

pro pause
pause

pro
pro 5) New-added *SHOW CONNECITON* command
pro
pro We can execute the SHOW CONNECITON command directly in the SQL*Plus prompt on 23ai ...
pro

pro show connection netservicenames
pro
show connection netservicenames

pro pause
pause

pro show connection netservicenames free
pro
show connection netservicenames free

pro pause
pause

pro show connection netservicenames listener_free
pro
show connection netservicenames listener_free

pro pause
pause

pro exit
exit